## RESTHeart simple security configuration file.

## look at undertow documentation for information about predictates syntax 
## http://undertow.io/documentation/core/predicates-attributes-handlers.html

## the special role $unauthenticated allows to give permissions without requiring authentication


---
#users:
#    - userid: michal.suchecki@gmail.com
#      password: secret
#      roles: [admin]

collectionusers:
  dbname: naszadm
  collection: accounts
  useridprop: email

permissions:
    - role: sysadmin
      predicate: path-prefix[path="/"]

    - role: administrator
      predicate: path-prefix[path="/"]

    - role: $unauthenticated
      predicate: path-prefix[path="/publicdb/"] and method[value="GET"]
      
    - role: $unauthenticated
      predicate: path[path="/integrationtestdb/coll1"] and method[value="GET"]
      
    - role: users
      predicate: regex[pattern="/.*/.*", value="%R", full-match=true] and method[value="GET"]
      
    - role: users
      predicate: path-prefix[path="/publicdb/{username}/"]